### ISSUE TITLE
gauge responsiveness

### ISSUE THREAD

**Issue by thirstyone** [Pygmalion69/Gauge#4]
could you please add some comments in the code, showing how to control the needle responsiveness (if it's at all possible) or add some controls to change the arrow speed?

**Comment by Pygmalion69** [comment]
The needle moves when its value differs from the requested value and the delta time (time since last move) has exceeded a certain interval. As you can see, this interval is hardcoded (5 ms). I should create a setter for this.

You can set the needle value immediately with setValue(&lt;float&gt;). Furthermore, you can create an animation by calling this method from a thread of your own.

**Comment by Pygmalion69** [comment]
I've added a couple of setters for the delta time interval (decrease to speed up) and the step size (increase to speed up).
