### ISSUE TITLE
Change gauze size

### ISSUE THREAD

**Issue by YashNagayach** [Pygmalion69/Gauge#8]
How can I change the gauge size... It is full circle right now but I want 270 degree not full 360.
Any suggestions?

**Comment by Pygmalion69** [comment]
Try to declare your attributes so that totalNicks * valuePerNick / (maxValue - minValue) &asymp; 360 / 270 *and* totalNicks is a multiple of valuePerNick.

`gauge:maxValue="1000"`
 `gauge:minValue="0"`
 `gauge:totalNicks="130"`
`gauge:valuePerNick="10"`

![gauge_issue_8](https://user-images.githubusercontent.com/6958566/41789437-94018c88-764f-11e8-9079-ed55c9c62e6d.png)
